CREATE DATABASE IF NOT EXISTS  burgers_db;
USE DATABASE burgers_db;
CREATE TABLE burgers (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    burger_name VARCHAR(50) NOT NULL DEFAULT '',
    devoured BOOLEAN NOT NULL DEFAULT false
);